{ config, pkgs, ... }:
{
  imports = [
    ./home-manager.nix # home manager configuration
    ./hardware-configuration.nix # autogenerated, do not touch
    ./base-config.nix # Standard config until I break things up
 #   ./boot.nix # bootloader, plymouth
 #   ./networking.nix # hostname, network manager
 #   ./locale.nix # time zone, locale, keyboard layout
 #   ./graphics.nix # graphic drivers, vulkan, hardware acceleration
 #   ./audio.nix # audio server
 #   ./users.nix # users, groups, default shell, packages
 #   ./packages.nix # system packages
 #   ./gui.nix # desktop environment / window manager
  ];
(...)
}
